name: CI actions

on:
  push:
    branches: [main, QA, Development]
  pull_request:
    branches: [main, QA, Development]

jobs:
  CI:
    runs-on: ubuntu-latest

    env:
      VITE_API_URL: http://localhost:3000
      VITE_FIREBASE_API_KEY: test_key

    strategy:
      matrix:
        node-version: [18]
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change to APP directory
        run: cd APP
        shell: bash

      - name: Install dependencies
        working-directory: ./APP
        run: npm ci

      - name: Build frontend
        working-directory: ./APP
        run: npm run build

      - name: Start frontend
        working-directory: ./APP
        run: npm run preview &

      - name: Wait for frontend to be ready
        working-directory: ./APP
        run: npx wait-on http://localhost:5173