name: CI actions

on:
  push:
    branches: [main, QA, Development]
  pull_request:
    branches: [main, QA, Development]

jobs:
  CI:
    runs-on: ubuntu-latest

    env:
      VITE_API_URL: http://localhost:3000
      VITE_SECRET_KEY: prueba

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Start frontend
        run: npm run preview &
        env:
          NODE_ENV: test

      - name: Wait for frontend to be ready
        run: |
            echo "Esperando que el frontend esté listo..."
            timeout 120 bash -c 'until curl -f http://localhost:5173; do sleep 2; done'
            echo "Frontend está listo!"

      - name: Run Cypress E2E tests
        run: npm run cy:run

      - name: Verify E2E Coverage
        run: npm run cy:verify-coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-e2e-coverage
          path: coverage
